name: Bugs

data_dump: dumps/match/Bugs
#train:
#  texts: MAG/train_texts.npy
#  labels: MAG/train_labels.npy
#
#valid:
#  size: 70534

#test:
#  texts: MAG/test_texts.npy

embedding:
  emb_init:

hierarchy: data/Bugs/bugs_tax.txt

output:
  res: dumps/match/Bugs/results

labels_binarizer: ignore_please
taxonomy_path: data/Bugs/bugs_tax.txt

model:
  emb_size: 100
