stratifiedCV: 3
n_repeats: 2
objective: "multilabel" # multiclass / multilabel

dataset: "amazon"
taxonomy_path: "data/Amazon/amazon_tax.txt"

remove_garbage: true
stop_words_removal: true

MAX_FEATURES: 30000
gridsearchCV_SPLITS: 5
retrain: true
SVM_GRID_PARAMS:
  estimator__C: [ 0.1, 1, 5, 10 ]
  estimator__max_iter: [ 500, 1000, 2000, 5000 ]
