stratifiedCV: 3
n_repeats: 1
objective: "multiclass" # multiclass / multilabel

dataset: "bgc"
taxonomy_path: "data/BGC/bgc_tax.txt"

remove_garbage: false
stop_words_removal: false

MAX_FEATURES: 30000
gridsearchCV_SPLITS: 5
retrain: true
SVM_GRID_PARAMS:
  estimator__C: [ 0.01, 0.1, 1, 5, 10 ]
  estimator__max_iter: [ 100, 200, 500, 1000, 2000 ]