name: htc-survey
channels:
  - pytorch
  - huggingface
  - conda-forge
  - defaults
dependencies:
  - click=8.1.3
  - fasttext=0.9.2
  - gensim=4.2.0
  - joblib=1.1.0
  - nltk=3.6.7
  - numpy=1.22.3
  - pip=21.2.4
  - python=3.10.4
  - pytorch=1.11.0
  - regex=2022.4.24
  - requests=2.27.1
  - rsa=4.8
  - sacremoses=master
  - scikit-learn=1.1.1
  - scipy=1.8.1
  - seaborn=0.11.2
  - tensorboard=2.9.0
  - tokenizers=0.11.4
  - torchmetrics=0.9.0
  - torchtext=0.12.0
  - tqdm=4.64.0
  - transformers=4.18.0
  - yaml=0.2.5
  - pip:
      - beautifulsoup4==4.11.1
      - networkx==2.8.6
      - pandas==1.4.3
      - pydot==1.4.2
      #- pygraphviz==1.10
      - pyyaml==6.0
      - spacy==3.3.1
      - stop-words==2018.7.23
